### ISSUE TITLE
Autocomplete list priority

### ISSUE THREAD

**Issue by cggit** [jason-pomerleau/vscode-wordpress-toolbox#18]
When enabled the snippets take priority over some key php autocomplete real-estate. Id like if(){} to be at the top. Is there a workaround for this?

<img width="388" alt="Screen Shot 2022-10-14 at 10 53 31 AM" src="https://user-images.githubusercontent.com/1779421/195877427-1eb841b5-6445-481d-b711-39535e753587.png">

**Comment by jason-pomerleau** [comment]
The Emmett-style abbreviations for ifame_footer, is_favicon, is_feed are "if". I will need to figure out how to prevent these from being added as prefixes, as you're right - php's if should take priority. Might take me a bit to get to this, give me a week.

**Comment by jason-pomerleau** [comment]
Hi @cggit, I've released a new update which includes a fix for this.
