### ISSUE TITLE
Is it possible to see all possible arguments?

### ISSUE THREAD

**Issue by Jebble** [jason-pomerleau/vscode-wordpress-toolbox#3]
I had a similar extension voor Sublime Text 3 and completing the snippets in ST3 would give me the function including an array of all the possible arguments. Functions like wp_nav_menu take a lot of possible arguments and it'd be nice not to have to open the documentation all the time.

If this is possible but you need help i'll be happy to do so if someone quickly explains how :)!

**Comment by jason-pomerleau** [comment]
Hi @Jebble, sorry for the delayed reply. I would like to have this feature too. The snippet JSON is built using a proprietary script, and I've been having some issues getting it working for function arguments that are associative arrays. As soon as I get more time to work on it, I'll try to build support for these args.
